# Generated by Django 4.2.4 on 2023-08-24 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 13, 32, 23, 811370, tzinfo=datetime.timezone.utc)),
        ),
    ]
